USE [master]
GO

/****** Object:  Database [slam2018JouetAVSG]    Script Date: 03/13/2018 17:01:41 ******/
CREATE DATABASE [slam2018JouetAVSG] ON  PRIMARY 
( NAME = N'slam2018JouetAVSG', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\slam2018JouetAVSG.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'slam2018JouetAVSG_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\slam2018JouetAVSG_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [slam2018JouetAVSG] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [slam2018JouetAVSG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [slam2018JouetAVSG] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET ARITHABORT OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [slam2018JouetAVSG] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [slam2018JouetAVSG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [slam2018JouetAVSG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET  DISABLE_BROKER 
GO

ALTER DATABASE [slam2018JouetAVSG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [slam2018JouetAVSG] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [slam2018JouetAVSG] SET  READ_WRITE 
GO

ALTER DATABASE [slam2018JouetAVSG] SET RECOVERY FULL 
GO

ALTER DATABASE [slam2018JouetAVSG] SET  MULTI_USER 
GO

ALTER DATABASE [slam2018JouetAVSG] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [slam2018JouetAVSG] SET DB_CHAINING OFF 
GO

